# Generated by Django 4.2.4 on 2023-08-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_course_coupon_code_course_coupon_disc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='0', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='usedcoupons',
            name='coupon_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
